---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# test cert installed using fqdn for name, so rename
# test/integration/default/data_bags/certificates/default-centos-72.json
# if updating
platforms:
  - name: centos-7.2

suites:
  - name: default
    data_bags_path: "test/integration/default/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/default/encrypted_data_bag_secret"
    run_list:
      - recipe[jhdc-mail::default]
    attributes:
      jhdc_mail:
        aliases:
          alice: charlie
