name             'jhdc-mail'
maintainer       'Jeff Hutchison'
maintainer_email 'jeff@jeffhutchison.com'
license          'Apache v2.0'
description      'Installs/Configures email'
long_description 'Installs/Configures Postfix, Dovecot, Spamassassin.'
version          '1.1.0'

depends 'postfix'
depends 'certificate'
depends 'firewalld'
depends 'yum-epel'
